In [1]:
import numpy as np

In [7]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [10]:
a[-1]

np.int64(4)

In [14]:
b=np.array([1,2,3,4,5,6,7,8,9])
b[0:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
c=b.copy()
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
d=b.view()
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
b[6]=12
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
d

array([ 1,  2,  3,  4,  5,  6, 12,  8,  9])

In [22]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=a.reshape(4,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
c=np.array([13,14,15])
d=np.concatenate((a,c))
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [36]:
np.array_split(d,2)

[array([1, 2, 3, 4, 5, 6, 7, 8]), array([ 9, 10, 11, 12, 13, 14, 15])]

In [37]:
np.where(d==4)

(array([3]),)

In [39]:
np.where(d%2==0)

(array([ 1,  3,  5,  7,  9, 11, 13]),)

In [41]:
c=np.array([3,4,2,10,5])
np.sort(c)

array([ 2,  3,  4,  5, 10])

In [43]:
c=np.array([[2,3,1,5],[5,1,2,4]])
np.sort(c)

array([[1, 2, 3, 5],
       [1, 2, 4, 5]])

In [45]:
c=np.array(['apple','orange','banana','mango'])
np.sort(c)

array(['apple', 'banana', 'mango', 'orange'], dtype='<U6')

In [51]:
np.random.randint(100)

54

In [60]:
np.random.rand(10)

array([0.94816557, 0.40611355, 0.83990966, 0.47199327, 0.70205729,
       0.68307144, 0.61261527, 0.46368747, 0.26721179, 0.74367061])

In [62]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [64]:
np.ones(2)

array([1., 1.])

In [66]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [68]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])